---
title: "Readme file"
author: "Robert Miller"
date: "October 30, 2016"
output:
  md_document:
    variant: markdown_github
---

# Readme

The files in the project support the following steps as defined in the project requirements:

You should create one R script called run_analysis.R that does the following.

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

The following files are the result of this project:

* 'CodeBook.md': Markdown file generated by processing the CodeBook.rmd file
* 'CodeBook.rmd': RStudio markdown file and source for the CodeBook.md file.
* Folder - 'Dataset': The source data for this project.  See below for more information
* 'Final_Exercise.Rproj': RStudio project file.
* 'README.md': Markdown file generated by processing the README.rmd file
* 'README.rmd': RSudio markdown file and source for the README.md file.
* 'run_analysis.R': The file used to process the soruce data and generate the tidy.csv output file.
* 'tidy.csv': The file generated by the run_analysis.R file.

For information concerning the source data in the Dataset folder, please refer to the README.txt file in the Dataset folder.

***Note:*** The package "reshape2" is required to execute the "run_analysis.R" script and is loaded (using require) or installed (if require fails) at the beginning of the script.  Require is used inlace of library as require allows for a handled recovery.  Please see the help for require or library (same document) for more information.
